### ISSUE TITLE
Test all demos on ARM

### ISSUE THREAD

**Issue by fhennig** [stackabletech/demos#18]
We already did some work on https://github.com/stackabletech/demos/tree/spike/demos-on-arm which leaves just the demos open not touched right now.

Shouldn't be to much. The test would be to have a ARM64 cluster and see if the demos work as expected (Be aware that it will only work for 23.11 and stackable-experimental contains ARM64 images and not multi arch for it)

**Comment by adwk67** [comment]
```[tasklist]
### Tasks
- [ ] hdfs/hbase cycling: works, but stackable stacklet list endpoints don't open
```

**Comment by sbernauer** [comment]
@adwk67 would you be willing to switch `docker.stackable.tech/demos/pyspark-k8s-with-kafka-and-iceberg:3.3.0-stackable0.2.0` to pull the deps using `spec.deps.packages` similar to the following? This way it should (tm) work (and a thing we want anyway I guess :) )

Using Spark 3.5 something like:
```
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.3
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
```

**Comment by adwk67** [comment]
As discussed today, closing this with fix issues carried over into https://github.com/stackabletech/demos/issues/25 and https://github.com/stackabletech/demos/issues/26.
